---
title: "R Code for Lecture 6"
output: pdf_document
---

```{r, message = F, warning = F}
library(TSA)
library(ggplot2)
library(latex2exp)
```

## ARCH(1) Model

\[
X_{t}=\sigma_{t}\epsilon_{t},\epsilon_{t}\sim N(0,1)
\]
\[
\sigma_{t}^{2}=0.6+0.4X_{t-1}^{2}
\] 

```{r}
X <- garch.sim(alpha = c(0.6, 0.4), n = 1000)
Xsq <- X^2
sig2 <- 0.6 + 0.4*lag(Xsq)
arch.data <- data.frame(time = c(1:length(X)), Xt = X, Xsqt = Xsq, sig2t = sig2)
```

```{r}
acf(arch.data$Xt, na.action = na.pass)
acf(arch.data$Xsqt, na.action = na.pass)

fig11 <- ggplot(arch.data, aes(time)) + 
  geom_line(aes(y = Xt), size = 0.6, color = "dodgerblue3") +
  labs(title = "ARCH(1)", 
       x = TeX("$t$"), y = TeX("$X_t$")) +        
  theme(axis.title = element_text(family = "serif"),
        plot.title = element_text(hjust = 0.5, family = "serif", face = "bold"))
fig11

fig12 <- ggplot(arch.data, aes(time)) + 
  geom_line(aes(y = sqrt(sig2t)), size = 0.6, color = "dodgerblue3") +
  labs(title = "ARCH(1)", 
       x = TeX("$t$"), y = TeX("$\\sigma_t$")) +        
  theme(axis.title = element_text(family = "serif"),
        plot.title = element_text(hjust = 0.5, family = "serif", face = "bold"))
fig12

fig13 <- ggplot(arch.data, aes(Xt)) +
  geom_histogram(aes(y = ..density..), bins = 100, color="white", 
                 fill="dodgerblue3", 
                 alpha = 0.75, size = 0.1) + 
  stat_function(fun = dnorm, color = "darkred", size = 0.7,
                args = list(mean = mean(arch.data$Xt, 
                                        na.rm = T), 
                            sd = sd(arch.data$Xt, 
                                    na.rm = T))) +
  labs(title = TeX("Empirical Distribution of $X_t$"), 
       x = TeX("$X_t$"), y = "Density") +
  theme(axis.title = element_text(family = "serif"),
        plot.title = element_text(hjust = 0.5, family = "serif"))
fig13

y <- quantile(arch.data$Xt, c(0.25, 0.75), na.rm = T) 
x <- qnorm(c(0.25, 0.75))         
slope <- diff(y)/diff(x)             
int   <- y[1] - slope*x[1] 

fig14 <- ggplot(arch.data, aes(sample = Xt)) +
  geom_qq(alpha = 0.5, size = 3, color = "dodgerblue3") +
  geom_abline(intercept=int, slope=slope, color = "darkred", size = 1) +
  labs(title = TeX("Q-Q Plot of $X_t$"), 
       x = "Normal Quantile", y = TeX("Quantile of $X_t$")) +
  theme(axis.title = element_text(family = "serif"),
        plot.title = element_text(hjust = 0.5, family = "serif"))
fig14
```

## GARCH(1,1) Model
\[
X_{t}=\sigma_{t}\epsilon_{t},\epsilon_{t}\sim N(0,1)
\]
\[
\sigma_{t}^{2}=0.6+0.2X_{t-1}^{2}+0.2\sigma_{t-1}^{2}
\]

```{r}
X <- garch.sim(alpha = c(0.6, 0.2), beta = 0.2, n = 1000)
Xsq <- X^2
sig2 <- vector("numeric"); sig2[1] <- NA
for (t in 2:length(X)) {
  sig2[t] <- 0.6/(1-0.2) + 0.2*sum(Xsq[1:(t-1)]*0.2^c((t-2):0))
}
garch.data <- data.frame(time = c(1:length(X)), Xt = X, Xsqt = Xsq, sig2t = sig2)
```

```{r}
acf(garch.data$Xt, na.action = na.pass)
acf(garch.data$Xsqt, na.action = na.pass)

fig21 <- ggplot(garch.data, aes(time)) + 
  geom_line(aes(y = Xt), size = 0.6, color = "dodgerblue3") +
  labs(title = "GARCH(1,1)", 
       x = TeX("$t$"), y = TeX("$X_t$")) +        
  theme(axis.title = element_text(family = "serif"),
        plot.title = element_text(hjust = 0.5, family = "serif", face = "bold"))
fig21

fig22 <- ggplot(garch.data, aes(time)) + 
  geom_line(aes(y = sqrt(sig2t)), size = 0.6, color = "dodgerblue3") +
  labs(title = "GARCH(1,1)", 
       x = TeX("$t$"), y = TeX("$\\sigma_t$")) +        
  theme(axis.title = element_text(family = "serif"),
        plot.title = element_text(hjust = 0.5, family = "serif", face = "bold"))
fig22

fig23 <- ggplot(garch.data, aes(Xt)) +
  geom_histogram(aes(y = ..density..), bins = 100, color="white", 
                 fill="dodgerblue3", 
                 alpha = 0.75, size = 0.1) + 
  stat_function(fun = dnorm, color = "darkred", size = 0.7,
                args = list(mean = mean(garch.data$Xt, 
                                        na.rm = T), 
                            sd = sd(garch.data$Xt, 
                                    na.rm = T))) +
  labs(title = TeX("Empirical Distribution of $X_t$"), 
       x = TeX("$X_t$"), y = "Density") +
  theme(axis.title = element_text(family = "serif"),
        plot.title = element_text(hjust = 0.5, family = "serif"))
fig23

y <- quantile(garch.data$Xt, c(0.25, 0.75), na.rm = T) 
x <- qnorm(c(0.25, 0.75))         
slope <- diff(y)/diff(x)             
int   <- y[1] - slope*x[1] 

fig24 <- ggplot(garch.data, aes(sample = Xt)) +
  geom_qq(alpha = 0.5, size = 3, color = "dodgerblue3") +
  geom_abline(intercept=int, slope=slope, color = "darkred", size = 1) +
  labs(title = TeX("Q-Q Plot of $X_t$"), 
       x = "Normal Quantile", y = TeX("Quantile of $X_t$")) +
  theme(axis.title = element_text(family = "serif"),
        plot.title = element_text(hjust = 0.5, family = "serif"))
fig24
```